### ISSUE TITLE
Release latest cookbook to supermarket

### ISSUE THREAD

**Issue by elliott-davis** [ceph/ceph-cookbook#188]
@guilhem seems to be the maintainer of the ceph cookbook in the supermarket.  Would it be possible to push the latest release (0.2.1) up?

**Comment by guilhem** [comment]
@elliott-davis you are right, we have some delay on supermarket.
@hufman what doo you think about it?

**Comment by hufman** [comment]
The Ceph cookbook feels very stable for Debian and Ubuntu installs. There's one issue for the 0.9 milestone referring to Centos installations, and some feature requests for the 1.0 milestone.
The current version is certainly much better than the marketplace version, and I think an update would be perfectly fine.

**Comment by jjasghar** [comment]
Awesome, the Openstack-Chef project would love to see this pushed up ASAP. Gotta love being downstream!

Thanks, and keep up the good work yall!

**Comment by jjasghar** [comment]
:+1: I tried pinging yall on the oftc.net, any chance we can get it pushed up today?

**Comment by cmluciano** [comment]
+1 on getting the new hotness in the supermarket. There are a lot of great changes that we could use. Thanks for all of your efforts! :)

**Comment by tyler-ball** [comment]
Yes, I would appreciate if this was also pushed!

**Comment by guilhem** [comment]
I will push it today ;)

**Comment by guilhem** [comment]
fixed by 3fab16979edb3d2e905625be658ce0512c928b26

**Comment by guilhem** [comment]
IMHO, 0.9 isn't achieve because of centos compatibility.
But we really have to push new version more regulary.

I hope for a 0.9 version in less than 1 month and a 1.0 just after ;)
